[package]
name = "k8s-learning"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
diesel = { version = "2.3.3", features = ["postgres"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
